apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kltn-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/argargargtbn01/helm-chart.git
    targetRevision: main
    path: KLTN/argocd-config
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true